In [1]:
import numpy as np
import pandas as pd

In [143]:
data=pd.read_csv('pokemon.csv')
data.tail()

#                 Name   Type 1 Type 2  Total  HP  Attack  Defense  \
795  719              Diancie     Rock  Fairy    600  50     100      150   
796  719  DiancieMega Diancie     Rock  Fairy    700  50     160      110   
797  720  HoopaHoopa Confined  Psychic  Ghost    600  80     110       60   
798  720   HoopaHoopa Unbound  Psychic   Dark    680  80     160       60   
799  721            Volcanion     Fire  Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True

In [3]:
data.shape

(800, 13)

In [6]:
X=data.drop('Legendary',axis=1)
X.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  
0       65       65     45           1  
1       80       80     60           1  
2      100      100     80           1  
3      122      120     80           1  
4       60       50     65           1

In [13]:
Names=data['Name']
Type=data[['Type 1','Type 2']]
print(Names.head(),Type.head())

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object   Type 1  Type 2
0  Grass  Poison
1  Grass  Poison
2  Grass  Poison
3  Grass  Poison
4   Fire     NaN


In [16]:
X=data.drop(['Name','Type 1','Type 2','Legendary'],axis=1)
X.head()

#  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation
0  1    318  45      49       49       65       65     45           1
1  2    405  60      62       63       80       80     60           1
2  3    525  80      82       83      100      100     80           1
3  3    625  80     100      123      122      120     80           1
4  4    309  39      52       43       60       50     65           1

In [20]:
y=data['Legendary']
y=np.where(y==True,1,0)
y[:5]

array([0, 0, 0, 0, 0])

In [28]:
def feature_Scaling(X):
    X=(X-X.mean())/X.std()
    return X
X=feature_Scaling(X)

In [35]:
X=np.append(np.ones([X.shape[0],1]),X,axis=1)
print(X.shape)
y=np.array(y).reshape([-1,1])
print(y.shape)

(800, 10)
(800, 1)


In [36]:
X_train=X[:640]
X_train.shape

(640, 10)

In [37]:
X_test=X[640:]
X_test.shape

(160, 10)

In [38]:
y_train=y[:640]
y_train.shape

(640, 1)

In [39]:
y_test=y[640:]
y_test.shape

(160, 1)

In [62]:
theta=np.zeros((X.shape[1],1))
theta.shape

(10, 1)

In [50]:
def sigmoid(z):
    return 1/(1+np.exp(-z))


In [68]:
def lrcost(X,y,theta):
    m=len(y)
    
    cost=(-1/(m))*(y*np.log(sigmoid(np.dot(X,theta)))+(1-y)*np.log(1-sigmoid(np.log(np.dot(X,theta))))).sum()
    return cost
    

In [69]:
cost=lrcost(X_train,y_train,theta)
cost

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


0.04657082619387132

In [238]:
def gradient_descent(X,y,theta,lr=1,epochs=2000):
    m=len(y)
    
    J_history=[]
    for _ in range(epochs):
        cost=lrcost(X,y,theta)
        grad=(1/m)*np.dot(X.T,sigmoid(np.dot(X,theta))-y)
        theta=theta-lr*grad
        J_history.append(cost)
    return J_history,theta
        

In [239]:
cost,new_theta=gradient_descent(X_train,y_train,theta)
new_theta

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in log
  after removing the cwd from sys.path.


array([[-6.68066949],
       [ 4.70842096],
       [ 1.03215956],
       [ 0.5874283 ],
       [-0.07476556],
       [ 0.66530479],
       [ 0.91113227],
       [ 0.8971603 ],
       [ 1.22916218],
       [-3.65493637]])

In [240]:
def predict(X,y):
    cost,new_theta=gradient_descent(X_train,y_train,theta)
    m=len(y)
    pred=np.dot(X,new_theta)
    
    return (np.where(np.dot(X,new_theta)>=0.5,1,0))
    

In [241]:
pre=predict(X_test,y_test)
print(pre)


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in log
  after removing the cwd from sys.path.


[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]]


In [242]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,pre)
acc

0.93125

In [243]:
Names_test=Names[640:]
Names_test.shape

(160,)

In [244]:
Type_test=Type[640:]
Type_test.shape

(160, 2)

In [245]:
Type_test=np.array(Type_test)
print(Type_test[0][:])

['Psychic' nan]


In [246]:
for i in range(160):
    if(pre[i]==0):
        print("{} is {} Type and is not a Legendary Pokemon".format(Names_test[i+640],Type_test[i][:]))
    else:
        print("{} is {} Type and is a Legendary Pokemon".format(Names_test[i+640],Type_test[i][:]))

Reuniclus is ['Psychic' nan] Type and is not a Legendary Pokemon
Ducklett is ['Water' 'Flying'] Type and is not a Legendary Pokemon
Swanna is ['Water' 'Flying'] Type and is not a Legendary Pokemon
Vanillite is ['Ice' nan] Type and is not a Legendary Pokemon
Vanillish is ['Ice' nan] Type and is not a Legendary Pokemon
Vanilluxe is ['Ice' nan] Type and is not a Legendary Pokemon
Deerling is ['Normal' 'Grass'] Type and is not a Legendary Pokemon
Sawsbuck is ['Normal' 'Grass'] Type and is not a Legendary Pokemon
Emolga is ['Electric' 'Flying'] Type and is not a Legendary Pokemon
Karrablast is ['Bug' nan] Type and is not a Legendary Pokemon
Escavalier is ['Bug' 'Steel'] Type and is not a Legendary Pokemon
Foongus is ['Grass' 'Poison'] Type and is not a Legendary Pokemon
Amoonguss is ['Grass' 'Poison'] Type and is not a Legendary Pokemon
Frillish is ['Water' 'Ghost'] Type and is not a Legendary Pokemon
Jellicent is ['Water' 'Ghost'] Type and is not a Legendary Pokemon
Alomomola is ['Water' n

## Misclassified points

In [247]:
pre-y_test

array([[ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 0],
       [-1],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [-1],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 1],
       [ 1],
       [ 1],

In [251]:
for i in range(0,160):
    if((pre[i]-y_test[i])!=0):
        print("{} is a Misclassified Pokemon".format(Names_test[640+i]))

Hydreigon is a Misclassified Pokemon
Volcarona is a Misclassified Pokemon
Terrakion is a Misclassified Pokemon
LandorusTherian Forme is a Misclassified Pokemon
KeldeoOrdinary Forme is a Misclassified Pokemon
KeldeoResolute Forme is a Misclassified Pokemon
MeloettaAria Forme is a Misclassified Pokemon
MeloettaPirouette Forme is a Misclassified Pokemon
Genesect is a Misclassified Pokemon
Goodra is a Misclassified Pokemon
Volcanion is a Misclassified Pokemon
